version: '3'

networks:
  backend:
    driver: bridge

services:
  quacker:
    image:  zgldh/kafka-quacker:1.0.0
    environment:
      QUACKER_BOOTSTRAP_SERVER: $QUACKER_BOOTSTRAP_SERVER
      QUACKER_SECURITY_PROTOCOL: $QUACKER_SECURITY_PROTOCOL
      QUACKER_KEYSTORE: /certificates/keystore
      QUACKER_KEYSTORE_PASSWORD: $QUACKER_KEYSTORE_PASSWORD
      QUACKER_KEY_PASSWORD: $QUACKER_KEY_PASSWORD
      QUACKER_TRUSTSTORE: /certificates/truststore
      QUACKER_TRUSTSTORE_PASSWORD: $QUACKER_TRUSTSTORE_PASSWORD
      QUACKER_TOPIC: $QUACKER_TOPIC
      QUACKER_CLIENTID: $QUACKER_CLIENTID
      QUACKER_INTERVAL: $QUACKER_INTERVAL
      QUACKER_DATAFILE: /data.json
      QUACKER_DRYRUN: $QUACKER_DRYRUN
    networks:
      - backend
    volumes:
      - $QUACKER_KEYSTORE:/certificates/keystore
      - $QUACKER_TRUSTSTORE:/certificates/truststore
      - $QUACKER_DATAFILE:/data.json
